repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: debug-statements
    language_version: python3
