name: Publish varmeth to PyPI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions to PyPI
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build Package and Check
        run: |
          python -m pip install --upgrade wheel twine
          python pip wheel --no-deps -w dist .
          python -m twine check dist/*

      - name: Deploy to PyPi
        uses: pypa/gh-action-pypi-publish@1.8.11
        with:
          user: __token__
          password: ${{ secrets.pypi_varmeth }}
